#!/bin/bash
read -p "WIPE DISK...?"
read -p "THIS SCRIPT WIPES DISK..."
sgdisk -Z /dev/nvme0n1
sgdisk -n 0::+512M -n 0:: /dev/nvme0n1
sed -i 's/#Color/Color\nILoveCandy/' /etc/pacman.conf
cryptsetup luksFormat --batch-mode /dev/nvme0n1p2
cryptsetup open /dev/nvme0n1p2 ct
mkfs.fat /dev/nvme0n1p1
mkfs.ext4 /dev/mapper/ct
mount /dev/mapper/ct /mnt
mount -o umask=0077 -m /dev/nvme0n1p1 /mnt/boot
fallocate -l 8G /mnt/sf
chmod 600 /mnt/sf
mkswap /mnt/sf
swapon -p 10 /mnt/sf
mkdir -p /mnt/etc/mkinitcpio.conf.d/
cat > /mnt/etc/mkinitcpio.conf.d/c.conf <<😈
HOOKS=(base udev autodetect microcode modconf keyboard block encrypt filesystems)
😈
pacstrap -KP /mnt base networkmanager sudo vi vim alacritty ttf-nerd-fonts-symbols noto-fonts-emoji terminus-font mako openssh inetutils exfatprogs ripgrep jq bc less eza bat fzf zoxide net-tools zram-generator intel-media-driver vulkan-intel intel-gmmlib pipewire pipewire-alsa pipewire-jack pipewire-pulse brightnessctl playerctl rofi fuzzel waybar chromium firefox firefox-ublock-origin btop mousepad flatpak swaylock niri wl-clipboard linux linux-firmware-intel linux-firmware-atheros intel-ucode
efibootmgr -c -d "/dev/nvme0n1" -p 1 -l "\vmlinuz-linux" -u "cryptdevice=/dev/nvme0n1p2:ct root=/dev/mapper/ct rw initrd=\initramfs-linux.img"
arch-chroot /mnt bash <<😈
sed -i 's/fmask=0077/noauto,fmask=0077/' /etc/fstab
sed -i '/\bext4\b/ s/\brelatime\b/noatime/g' /etc/fstab
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers
echo "vm.swappiness=10" >> /etc/sysctl.d/99-swappiness.conf
cat << 'EOF' > /etc/systemd/zram-generator.conf
[zram0]
zram-size = ram / 2
compression-algorithm = lz4
swap-priority = 100
fs-type = swap
EOF
cat <<EOF > /etc/bash.bashrc
source <(fzf --bash)
source <(zoxide init bash)
EOF
systemctl enable NetworkManager fstrim.timer
echo
echo "💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀"
echo
😈
arch-chroot /mnt
